import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Arrow from "./components/Arrow";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "UC-03 Gulshan Town ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
        {children}
        <Arrow/>
      </body>
    </html>
  );
}
